[package]
name = "rust_test_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
android-activity = { version = "0.6", features = ["game-activity"] }
ndk = "0.9"
log = "0.4"
android_logger = "0.14"

[profile.release]
opt-level = 3        # Optimasi kecepatan eksekusi maksimal
lto = true           # Link-Time Optimization (buang kode mati antar crate)
codegen-units = 1    # Kompilasi monolitik agar hasil binary lebih efisien
panic = "abort"      # Hilangkan overhead stack unwinding
strip = true         # Hapus symbol debug biar biner .so super kecil & cepat diload
