[package]
name = "rust_test_app"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
android-activity = { version = "0.6", features = ["game-activity"] }
ndk = "0.9"
log = "0.4"
bevy = "0.19"
bevy_svg = "0.19"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
