name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: aarch64-linux-android

      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: Build Rust (.so)
        run: cargo ndk -t arm64-v8a -P 26 -o android/app/src/main/jniLibs build --release

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.8.0'

      - name: Build APK
        working-directory: android
        run: gradle assembleRelease

      - uses: actions/upload-artifact@v4
        with:
          name: rusttest-apk
          path: android/app/build/outputs/apk/release/*.apk

      - name: Cek isi APK
        run: unzip -l android/app/build/outputs/apk/release/*.apk | grep -E "assets/|\.so"

      - name: Ukuran APK
        run: ls -lh android/app/build/outputs/apk/release/*.apk
